output_folder = './data3/'
input_folder = 'paper/'
text_graph_name = 'text_graph2.pkl'
word_edge_graph = 'word_word_edges2.pkl'
resource_path = 'resources/labels'
text_graph_file_name = 'Text Graph'
loss_plot_name = 'Loss per epochs'
accuracy_plot_name = 'Accuracy per epochs'